[package]
name = "concurrency"
version = "0.1.0"
authors = ["Eli <e_corrales2003@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
