[package]
name = "tinymd"
version = "0.1.0"
authors = ["eliezerc"]
edition = "2018"
description = "a mostly useless markdown compiler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
